### ISSUE TITLE
Initiative Tracker

### ISSUE THREAD

**Issue by KjartanE** [sam-warren/DMTools#1]
Fully function initiative tracker 

- [ ] Functioning list
- [ ] Add Player/Monster Button 
- [ ] Dialog popup with form filler
- [ ] Save Player/Monster Stats 
- [ ] Health Tracker on NPCs
- [ ] Initiative Roller with Bonus modifier
- [ ] Buff/Effect Tracker for each item
- [ ] Highlight list tracker, with next button
